// GENERATED by tools/embed_web.py from web/ - do not edit by hand.
#pragma once

struct WebAsset { const char *path, *mime, *body; };

static const WebAsset WEB_ASSETS[] = {
  {"/app.js", "application/javascript; charset=utf-8", R"WEB_ASSET('use strict';

// Must match firmware/SignBoard/config.h
const W = 128;
const H = 64;
const WS_PORT = 81;

const PEN_WIDTH = 2;          // stroke width in OLED pixels
const SEND_INTERVAL_MS = 40;  // live-stream throttle; one I2C frame push takes ~25 ms

/**
 * Threshold RGBA pixels to pure black/white *in place* (so the canvas shows exactly
 * what the OLED will) and pack them into SSD1306 page format:
 * 8 pages x 128 columns, byte = (y >> 3) * 128 + x, bit = y & 7 (LSB = top).
 */
function toBitmap(px) {
  const out = new Uint8Array(W * H / 8);
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      const i = (y * W + x) * 4;
      const on = px[i] > 127;
      px[i] = px[i + 1] = px[i + 2] = on ? 255 : 0;
      if (on) out[(y >> 3) * W + x] |= 1 << (y & 7);
    }
  }
  return out;
}

if (typeof module !== 'undefined') module.exports = { toBitmap, W, H };  // for tools/test_bitmap.js
else init();

function init() {
  const canvas = document.getElementById('pad');
  const ctx = canvas.getContext('2d', { willReadFrequently: true });
  const statusEl = document.getElementById('status');
  const liveEl = document.getElementById('live');

  // Served by the ESP32 -> same host. Served elsewhere (dev) -> ?host=<esp32-ip>.
  const host = new URLSearchParams(location.search).get('host') || location.hostname || 'signboard.local';
  const wsUrl = `ws://${host}:${WS_PORT}/`;

  let ws = null;
  let frame = null;      // latest packed 1024-byte bitmap
  let dirty = true;      // canvas changed since last pack
  let pending = false;   // frame should be delivered to the OLED
  let lastSent = 0;
  let pointerId = null;
  let last = null;

  ctx.lineWidth = PEN_WIDTH;
  ctx.lineCap = 'round';
  ctx.lineJoin = 'round';
  ctx.strokeStyle = '#fff';
  clear();

  // ---- Drawing (Pointer Events: finger, Apple Pencil and mouse alike) ----------

  function point(e) {
    const r = canvas.getBoundingClientRect();
    return [(e.clientX - r.left) * W / r.width, (e.clientY - r.top) * H / r.height];
  }

  canvas.addEventListener('pointerdown', (e) => {
    if (pointerId !== null) return; // one stroke at a time, ignore extra fingers/palm
    pointerId = e.pointerId;
    canvas.setPointerCapture(pointerId);
    last = point(e);
    ctx.fillStyle = '#fff';
    ctx.beginPath();
    ctx.arc(last[0], last[1], PEN_WIDTH / 2, 0, Math.PI * 2);
    ctx.fill();
    dirty = true;
  });

  canvas.addEventListener('pointermove', (e) => {
    if (e.pointerId !== pointerId) return;
    const p = point(e);
    ctx.beginPath();
    ctx.moveTo(last[0], last[1]);
    ctx.lineTo(p[0], p[1]);
    ctx.stroke();
    last = p;
    dirty = true;
  });

  const endStroke = (e) => { if (e.pointerId === pointerId) pointerId = null; };
  canvas.addEventListener('pointerup', endStroke);
  canvas.addEventListener('pointercancel', endStroke);

  // Stop iPad Safari pinch-zooming the page (it ignores user-scalable=no).
  document.addEventListener('gesturestart', (e) => e.preventDefault());

  // ---- Buttons ---------------------------------------------------------------

  function clear() {
    ctx.fillStyle = '#000';
    ctx.fillRect(0, 0, W, H);
    dirty = true;
  }

  document.getElementById('clear').addEventListener('click', clear);
  document.getElementById('submit').addEventListener('click', () => { pending = true; });
  liveEl.addEventListener('change', () => { if (liveEl.checked) pending = true; });

  // ---- Pack + send loop --------------------------------------------------------
  // Packs at most once per display frame and sends at most every SEND_INTERVAL_MS,
  // only when the previous frame has left the socket. Because `pending` stays set
  // until a send succeeds, the final frame of every stroke is always delivered.

  function tick(now) {
    if (dirty) {
      dirty = false;
      const img = ctx.getImageData(0, 0, W, H);
      frame = toBitmap(img.data);
      ctx.putImageData(img, 0, 0);
      if (liveEl.checked) pending = true;
    }
    if (pending && now - lastSent >= SEND_INTERVAL_MS &&
        ws && ws.readyState === WebSocket.OPEN && ws.bufferedAmount === 0) {
      ws.send(frame);
      pending = false;
      lastSent = now;
    }
    requestAnimationFrame(tick);
  }
  requestAnimationFrame(tick);

  // ---- WebSocket (auto-reconnect) ----------------------------------------------

  function setStatus(online) {
    statusEl.textContent = online ? `Connected · ${host}` : `Offline · retrying ${host}…`;
    statusEl.classList.toggle('online', online);
  }

  function connect() {
    ws = new WebSocket(wsUrl);
    ws.onopen = () => {
      setStatus(true);
      if (liveEl.checked) pending = true; // resync the OLED with the pad
    };
    ws.onclose = () => {
      setStatus(false);
      setTimeout(connect, 1000);
    };
    ws.onmessage = (e) => console.warn('[esp32]', e.data);
  }
  connect();
}
)WEB_ASSET"},
  {"/", "text/html; charset=utf-8", R"WEB_ASSET(<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="apple-mobile-web-app-title" content="SignBoard">
  <meta name="theme-color" content="#0b0d10">
  <title>SignBoard</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <header class="toolbar">
    <span id="status" class="status" role="status" aria-live="polite">Connecting…</span>
    <label class="toggle"><input type="checkbox" id="live" checked> Live</label>
    <button id="clear" type="button">Clear</button>
    <button id="submit" type="button" class="primary">Send</button>
  </header>

  <main class="stage">
    <!-- Drawn at the OLED's real resolution and scaled up, so what you see is what the OLED shows. -->
    <canvas id="pad" width="128" height="64" aria-label="Drawing pad mirrored to the OLED display"></canvas>
  </main>

  <script src="app.js"></script>
</body>
</html>
)WEB_ASSET"},
  {"/style.css", "text/css; charset=utf-8", R"WEB_ASSET(:root {
  color-scheme: dark;
  --bg: #0b0d10;
  --panel: #171a1f;
  --line: #2a2f37;
  --fg: #e8ecf1;
  --muted: #8a93a0;
  --accent: #38bdf8;
  --ok: #34d399;
  --bad: #f87171;
  --radius: 12px;
}

* { box-sizing: border-box; }

html, body { height: 100%; margin: 0; }

body {
  display: flex;
  flex-direction: column;
  overflow: hidden;
  overscroll-behavior: none;
  padding: env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left);
  background: var(--bg);
  color: var(--fg);
  font: 17px/1.2 -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
  -webkit-user-select: none;
  user-select: none;
  -webkit-touch-callout: none;
  -webkit-tap-highlight-color: transparent;
}

/* ---- Toolbar ---------------------------------------------------------------- */

.toolbar {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 12px;
  padding: 16px;
}

.status {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-right: auto;
  color: var(--muted);
}
.status::before {
  content: "";
  width: 10px;
  height: 10px;
  border-radius: 50%;
  background: var(--bad);
}
.status.online::before { background: var(--ok); box-shadow: 0 0 8px var(--ok); }

button,
.toggle {
  min-height: 52px; /* comfortably above the 44pt touch-target guideline */
  padding: 0 24px;
  border: 1px solid var(--line);
  border-radius: var(--radius);
  background: var(--panel);
  color: var(--fg);
  font: inherit;
  font-weight: 600;
  touch-action: manipulation;
}

button:active { transform: scale(0.97); }
button:focus-visible,
.toggle:focus-within { outline: 2px solid var(--accent); outline-offset: 2px; }

button.primary {
  border-color: transparent;
  background: var(--accent);
  color: #04121b;
}

.toggle {
  display: inline-flex;
  align-items: center;
  gap: 10px;
}
.toggle input {
  width: 22px;
  height: 22px;
  margin: 0;
  accent-color: var(--accent);
}

/* ---- Drawing pad ----------------------------------------------------------- */

.stage {
  flex: 1;
  min-height: 0;
  display: grid;
  place-items: center;
  padding: 8px 28px 28px;
  container-type: size;
}

#pad {
  /* Largest 2:1 box that fits the stage; height follows the 128x64 intrinsic ratio. */
  width: min(100cqw, 200cqh);
  height: auto;
  background: #000;
  border-radius: 4px;
  box-shadow: 0 0 0 12px #1b1f25, 0 24px 60px rgb(0 0 0 / 0.6); /* OLED bezel */
  image-rendering: pixelated;
  touch-action: none; /* no scroll / zoom while drawing */
  cursor: crosshair;
}
)WEB_ASSET"},
};
