#!/usr/bin/env python3
"""Embed web/ into firmware/SignBoard/web_assets.h so the ESP32 can serve the app.

Arduino IDE compiles a copy of the sketch folder, so the firmware cannot reach
../../web at build time. Re-run this after editing anything in web/:

    python tools/embed_web.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WEB = ROOT / "web"
OUT = ROOT / "firmware" / "SignBoard" / "web_assets.h"
MIME = {".html": "text/html", ".css": "text/css", ".js": "application/javascript"}
DELIM = "WEB_ASSET"  # raw-string delimiter, must not appear in the files

entries = []
for f in sorted(WEB.iterdir()):
    if f.suffix not in MIME:
        continue
    text = f.read_text(encoding="utf-8")
    if f'){DELIM}"' in text:
        raise SystemExit(f"{f.name} contains the raw-string terminator ){DELIM}\"")
    path = "/" if f.name == "index.html" else "/" + f.name
    entries.append(f'  {{"{path}", "{MIME[f.suffix]}; charset=utf-8", R"{DELIM}({text}){DELIM}"}},')

with open(OUT, "w", encoding="utf-8", newline="\n") as out:
    out.write(
        "// GENERATED by tools/embed_web.py from web/ - do not edit by hand.\n"
        "#pragma once\n\n"
        "struct WebAsset { const char *path, *mime, *body; };\n\n"
        "static const WebAsset WEB_ASSETS[] = {\n" + "\n".join(entries) + "\n};\n"
    )
print(f"wrote {OUT.relative_to(ROOT)} ({len(entries)} files)")
